# Note: this file was extracted from sdo_sdk_binaries_*_linux_x64.tar.gz,
#       file do_sdk_binaries_*_linux_x64/SupplyChainTools/docker_manufacturer/docker-compose.yml
#       and then customized with user, pw, etc.
version: "2.2"

services:

  manufacturer:
    build:
      context: $PWD/../sdo_sdk_binaries_linux_x64/SupplyChainTools/docker_manufacturer
      dockerfile: Dockerfile-manufacturer
    image: manufacturer
    container_name: manufacturer
    hostname: manufacturer
    restart: on-failure
    ports:
      # If you use a different port for the manufacturer, modify it here and in the healthcheck below.
      - "8039:8080"
    expose:
      - "8039"
    volumes:
      - ./keys:/keys:ro
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/intel_sdo
      # Modify these variables to reflect your username and password.
      SPRING_DATASOURCE_USERNAME: sdo
      SPRING_DATASOURCE_PASSWORD: sdo 
      # Modify these parameters to reflect your keystore path and password
      # Keys are stored on a shared volume, defined above, on your local hard disk.
      SDO_KEYSTORE: file://keys/sdo.p12
      SDO_KEYSTORE_PASSWORD: 123456
      # Uncomment and edit proxy configuration if your environment requires proxies.
      # http_proxy: http://yourProxy.yourCompany.com:80
      # https_proxy: http://yourProxy.yourCompany.com:443
      # Change TZ (timezone) to reflect your location.
      TZ: America/Los_Angeles
      # CATALINA_OPTS: -D<add any additional tomcat options here, if needed>
    healthcheck:
      # Modify port here if it was changed above.
      #test: curl -f http://localhost:8039/api/version
      #interval: 10s
      #timeout: 10s
      #retries: 1
      # BP: the healthcheck from Intel is always failing - they are investigating. In the mean time, disable it
      disable: true
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    build:
      context: $PWD/../sdo_sdk_binaries_linux_x64/SupplyChainTools/docker_manufacturer
      dockerfile: Dockerfile-mariadb
      # Uncomment and edit proxy configuration if your environment requires proxies.
      # args:
        # http_proxy: http://yourProxy.yourCompany.com:80
        # https_proxy: http://yourProxy.yourCompany.com:443
    container_name: mariadb
    hostname: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: intel_sdo
      # Modify these variables to reflect your configuration.
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_USER: sdo
      MYSQL_PASSWORD: sdo
      # Uncomment and edit proxy configuration if your environment requires proxies.
      # http_proxy: http://yourProxy.yourCompany.com:80
      # https_proxy: http://yourProxy.yourCompany.com:443
      # Change TZ (timezone) to reflect your location.
      TZ: America/Los_Angeles
    ports:
      - "3306:3306"
    expose:
      - "3306"
    healthcheck:
      # Modify user/password to match your configuration.
      test: mysql --user=sdo --password=sdo -e 'use intel_sdo; select * from v_rt_customer_public_key;'
      interval: 5s
      timeout: 3s
      retries: 10
